#pragma config(Motor, port1, leftTread, tmotorVex393_HBridge, openLoop)
#pragma config(Motor, port7, clawMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor, port9, slideMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor, port10, rightTread, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard !!*//

bool clawOpen = false; // Track claw state
bool lastClawButton = false;

task main()
{
while(true)
{
// --- Treads Control ---
motor[leftTread] = (vexRT[Btn5U] - vexRT[Btn5D]) * 100;
motor[rightTread] = (vexRT[Btn6U] - vexRT[Btn6D]) * 100;

// --- Slide Control ---
motor[slideMotor] = (vexRT[Btn7U] - vexRT[Btn7D]) * 100;

// --- Claw Toggle Control (Btn8U) ---
bool currentClawButton = vexRT[Btn8U];

if(currentClawButton && !lastClawButton)
{
// Toggle state
clawOpen = !clawOpen;
}
lastClawButton = currentClawButton;

// Set claw motor power
if(clawOpen)
{
motor[clawMotor] = 100; // Open
}
else
{
motor[clawMotor] = -100; // Close
}

wait1Msec(20); // Small delay to prevent CPU overload
}
}
